Replace sankey with alluvial plot
Nanostring-Biostats/GeoMxWorkflows pull request #27
Opened 2023-04-12 17:13 UTC by mahitha-raj

- Fixes bug in ggplot2 by replacing the sankey diagram with an alluvial plot
- Mirrors the fix uses in sDAS
- Adds the 'parcats' and 'easyalluvial' packages to NAMESPACE

Note: I used `target_demoData` for the post-QC Aulluvial plot because the text mentioned removing both (i) segments flagged by QC, and (ii) low detection rate. In the original workflow, post-QC `demoData` was used.

2023-04-13 20:19 UTC, NicoleEO requested changes
Line 108, remove the specification for version as GeoMxWorkflows update will be in the yet to be released 3.17. So just do BiocManager::install() and they should all play nice together with the default latest release version installed. I tested to make sure that's the case as well.

2023-04-14 23:45 UTC, mahitha-raj commented on NAMESPACE
> +import(easyalluvial)
Added https://github.com/Nanostring-Biostats/GeoMxWorkflows/pull/27/commits/6e59118975efcd1d211c0196e9ebd624d5c75bd0

2023-04-14 23:46 UTC, mahitha-raj commented on NAMESPACE
> +import(parcats)
Added https://github.com/Nanostring-Biostats/GeoMxWorkflows/pull/27/commits/6e59118975efcd1d211c0196e9ebd624d5c75bd0

2023-04-19 00:37 UTC, mahitha-raj commented on vignettes/GeomxTools_RNA-NGS_Analysis.Rmd
> +        offset_marginal_histograms = 0.7)
Removed offset as not required here and changed size of plot. Looks much better when knit!

2023-04-19 00:37 UTC, mahitha-raj commented on vignettes/GeomxTools_RNA-NGS_Analysis.Rmd
> +        offset_marginal_histograms = 0.7)
Looks better when knit now: 
![image](https://user-images.githubusercontent.com/17988388/232936382-d85658e7-18b0-4648-8bcd-dda248610735.png)

2023-04-19 00:38 UTC, mahitha-raj commented on vignettes/GeomxTools_RNA-NGS_Analysis.Rmd
> +        data_input = sampleOverview,
Thank you for the catch! Fixed [dc9c924](https://github.com/Nanostring-Biostats/GeoMxWorkflows/pull/27/commits/dc9c924bce140a555c457e182575d5a9b9340beb)

2023-04-19 00:39 UTC, mahitha-raj commented on vignettes/GeomxTools_RNA-NGS_Analysis.Rmd
> +datadir <- system.file("inst", "extdata", "WTA_NGS_Example",
Removed 'inst' and version.

2023-04-19 00:41 UTC, mahitha-raj commented
All changes have been made and re-tested the knit. Ready for a follow-up review @NicoleEO .

2023-04-20 23:29 UTC, maddygriz commented
@mahitha-raj @NicoleEO I fixed the DE plots. I added the changes here because I couldn't get the vignette to knit on the main branch due to the sankey issue. The alluvial plots look good!

2023-05-25 04:35 UTC, NicoleEO commented
Resolves issue #21

2023-05-25 04:49 UTC, NicoleEO approved these changes
Everything in here looks good @mahitha-raj and @maddygriz

2023-10-18 23:28 UTC, merged