say latest version instead of actual bioc version
Nanostring-Biostats/GeoMxWorkflows pull request #30
Opened 2023-10-03 15:25 UTC by maddygriz

resolves #29

2023-10-04 16:46 UTC, NicoleEO requested changes
Just leave the parentheses blank. This will download the latest version the user can get with their version of R. Using "LATEST.VERSION" will break building the vignette and we would need to rewrite tests.

2023-10-04 17:00 UTC, maddygriz commented
That code chunk isn't run in the vignette so it won't break things. But I will change that to be empty.

2023-10-05 16:37 UTC, NicoleEO commented
Approved, documentation update to let user know they should download latest version of bioc.

2023-10-05 16:38 UTC, NicoleEO approved these changes

2023-10-18 22:31 UTC, merged